name: run load_mapping_table.py

on:
  workflow_dispatch:
  schedule:
    - cron: "0 5 1 */2 *" # At 10:30 AM on day-of-month 1 in every 2nd month (UTC - 05:00)

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v2 # checkout the repository content to github runner

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12" # install the python version needed

      - name: install poetry and then dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install --no-root

      - name: execute python script
        env:
          BQ_JSON: ${{ secrets.BQ_SVA_JSON }}
        run: poetry run python load_mapping_table.py

      - name: commit files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add -A
          git diff-index --quiet HEAD || (git commit -a -m "refresed mapping table" --allow-empty)

      - name: push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
